controller_manager:
  ros__parameters:
    update_rate: 10

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      #type: joint_trajectory_controller/JointTrajectoryController
      type: forward_command_controller/forwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/jointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3

    command_interface:
      - position

    state_interface:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectory: true

gripper_controller:
  ros__parameters:
    joints:
      - joint_4
    interface_name: position

#    command_interface:
#      - position

#    state_interface:
#      - position

#    open_loop_control: true
#    allow_integration_in_goal_trajectory: true

